export const cardData = [
  {
    id: 1,
    name: "Sample Course 1",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 1",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 2,
    name: "Sample Course 2",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 2",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 3,
    name: "Sample Course 3",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 3",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 4,
    name: "Sample Course 4",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 4",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 5,
    name: "Sample Course 5",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 5",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 6,
    name: "Sample Course 6",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 6",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 7,
    name: "Sample Course 7",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 7",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 8,
    name: "Sample Course 8",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 8",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 9,
    name: "Sample Course 9",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 9",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 10,
    name: "Sample Course 10",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 10",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 11,
    name: "Sample Course 11",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 11",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
  {
    id: 12,
    name: "Sample Course 12",
    description: "This is a sample course description.",
    subtext: "Subtext for Card 12",
    progress: 0.25,
    isChecked: true,
    instructor: "John Doe",
    enrollmentStatus: "Open",
    duration: "8 weeks",
    schedule: "Mon & Wed, 6:00 PM - 8:00 PM",
    location: "Online",
    prerequisites: [
      "Basic Knowledge of Programming",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Intro to Web Development",
      "Basic Knowledge of Programming",
    ],
    syllabus: "Course syllabus goes here...",
  },
];
